name: test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        perl: [ '5.10', '5.30' ]
    name: Testing perl ${{ matrix.perl }} on ${{ matrix.os }}
    env:
      PERL_VERSION: ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v3
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: install dependencies by shell
        if: env.PERL_VERSION != '5.10'
        run: cpanm --installdeps .
      - name: install dependencies
        if: env.PERL_VERSION == '5.10'
        uses: perl-actions/install-with-cpanm@v1
        with:
          install: |
            LWP::UserAgent
            LWP::Protocol::https
            HTTP::Request::Common
            JSON
            Test::More
            Test::Mock::LWP
      - run: perl -V && perl Makefile.PL && make test
